=== HEHvidunge/w3tlabbar/L1/booklist.dtd
<!-- 

 booklist*
 book
  title
  author (name)
  publisher 
  year (year published)
reading
   start (date)
   finish (date)
rating (1-5 stars)`
cover
-->
<!ELEMENT booklist (month, book)>
  <!ELEMENT month (#PCDATA)>
  <!ELEMENT book (title, author, publisher, year, reading, rating, cover)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT author (#PCDATA)>
   <!ELEMENT publisher (#PCDATA)>
   <!ELEMENT year (#PCDATA)>
   <!ELEMENT reading (start,finish)>
   <!ELEMENT start (#PCDATA)>
   <!ELEMENT finish (#PCDATA)>
   <!ELEMENT rating (#PCDATA)>
   <!ELEMENT cover (EMPTY)>
     <!ATTLIST cover url CDATA #REQUIRED>

=== HEHvidunge/w3tlabbar/L1/august.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">

<booklist>
<month>August</month>
    <book>
        <author>Cat Jarman</author>
    <title>River Kings: A New History of Vikings from Scandinavia to
        the Silk Roads</title>
    <year>2022</year>
    <publisher>HarperCollins</publisher>
    <reading>
            <start> </start>
            <finish> </finish>
        </reading>			
    <rating> </rating> 
    <cover>url="/img/riverkings.jpg"/>
    </book>

    <book>
        <author>Hugh Kennedy</author>
    <title>The Great Arab Conquests How the Spread of Islam Changed
        the World We Live In</title>
    <year>2008</year>
    <publisher>Phoenix</publisher>
    <reading>
            <start> </start>
            <finish> </finish>
        </reading>			
    <rating> </rating> 
    <coverurl="/img/arabconquest.jpg"/>
    </book>

    <book>
        <author>William J. Bernstein</author>
    <title>A Splendid Exchange: How Trade Shaped the World</title>
    <year>
        2008</year>
    <publisher>Atlantic Monthly Press</publisher>
    <reading>
            <start> </start>
            <finish> </finish>
        </reading>			
    <rating> </rating> 
    <coverurl="/img/splendidexchange.jpg"/>
    </book>

    <book>
        <author>Brendan Simms</author>
    <title>Europe: The Struggle for Supremacy from 1453 to the
        Present</title>
    <year>2013</year>
    <publisher>Basic Books</publisher>
    <reading>
            <start> </start>
            <finish> </finish>
        </reading>			
    <rating> </rating> 
    <coverurl="/img/europe.jpg"/>
    </book>

    <book>
        <author>Dominic Sandbrook</author>
    <title>Who Dares Wins</title>
    <year>2020</year>
    <publisher>
        Penguin</publisher>
    <reading>
            <start> </start>
            <finish> </finish>
        </reading>			
    <rating> </rating> 
    <coverurl="/img/whodares.jpg"/>
    </book>
</booklist>

=== HEHvidunge/w3tlabbar/L1/june.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">

<booklist>

    <month>June</month>

    <book>
        <author>Ed Yong </author>
        <title> An Immense World: How Animal Senses Reveal the Hidden
        Realms Around Us</title>
        <year>2022</year>
        <publisher>Bodley Head</publisher>
        <reading>
            <start>20230601</start>
            <finish>20230614</finish>
        </reading>			
        <rating>3</rating> 
        <cover url="img/immenseworld.jpg"/>
    </book>

    <book>
        <author>Tom Holland </author>
        <title>Pax: War and Peace in Rome's Golden Age</title>
        <year>
        2023</year>
        <publisher>Abacus</publisher>
        <reading>
            <start>20230615</start>
            <finish>20230630</finish>
        </reading>			
        <rating>4</rating> 
        <cover url="img/pax.jpg"/>
    </book>

    <book>
        <author>James D. Tabor</author>
        <title>Paul and Jesus: How the Apostle Transformed
        Christianity</title>
        <year>2013</year>
        <publisher>Simon and Schuster </publisher>
        <reading>
            <start> </start>
            <finish> </finish>
        </reading>			
        <rating> </rating> 
        <cover url="img/paulandjesus.jpg"/>
    </book>
</booklist>

=== HEHvidunge/w3tlabbar/L1/july.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">
<booklist>
    <month>July</month>
    <book>
        <author>Peter Frankopan</author>
        <title>The Earth Transformed: An Untold History</title>
        <year> 2023</year>
        <publisher>Bloomsbury</publisher>
        <reading>
            <start> </start>
            <finish> </finish>
        </reading>
        <rating> </rating>
        <cover url="img/earthtransformed.jpg"/>
    </book>

    <book>
        <author>Edith Hall</author>
        <title>Introducing the Ancient Greeks: From Bronze Age Seafarers to Navigators of the
            Western Mind</title>
        <year>2015</year>
        <publisher>W. W. Norton and Company</publisher>
        <reading>
            <start> </start>
            <finish> </finish>
        </reading>
        <rating> </rating>
        <cover url="img/ancientgreeks.jpg"/>
    </book>

    <book>
        <author>Rana Mitter</author>
        <title>China's War With Japan, 1937-1945</title>
        <year>2014</year>
        <publisher> PENGUIN</publisher>
        <reading>
            <start> </start>
            <finish> </finish>
        </reading>
        <rating> </rating>
        <cover url="img/chinaswar.jpg"/>
    </book>
</booklist>
